### ISSUE TITLE
node 호스팅 서비스 사용하기

### ISSUE THREAD

**Issue by keesun** [SpingSproutAce/rtfeedback#18]
joyent 시도중

**Comment by keesun** [comment]
keesun-baik-ui-MacBook:rtfeedback2 keesunbaik$ git push joyent master
Counting objects: 12, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 3.66 KiB, done.
Total 8 (delta 5), reused 0 (delta 0)
remote: Starting node v0.4.7...
remote: 
remote: Failed to start new server.
remote: 
remote: \* \* \* tail of '/var/svc/log/site-node-service:default.log' \* \* *
remote:     at Function._load (module.js:266:25)
remote:     at require (module.js:348:19)
remote:     at Object.<anonymous> (/home/node/node-service/releases/20110702061403/node_modules/socket.io/lib/socket.io.js:12:14)
remote:     at Module._compile (module.js:404:26)
remote:     at Object..js (module.js:410:10)
remote:     at Module.load (module.js:336:31)
remote:     at Function._load (module.js:297:12)
remote:     at require (module.js:348:19)
remote:     at Object.<anonymous> (/home/node/node-service/releases/20110702061403/node_modules/socket.io/index.js:8:18)
remote: [ Jul  2 06:14:04 Stopping because all processes in service exited. ]
remote: [ Jul  2 06:14:04 Executing stop method (:kill). ]
remote: [ Jul  2 06:14:04 Executing start method ("env `cat /home/node/node-service/profile` /opt/nodejs/v0.4.7/bin/node /home/node/node-service/releases/20110702061403/server.js &"). ]
remote: [ Jul  2 06:14:04 Method "start" exited with status 0. ]
remote: 
remote: node.js:134
remote:         throw e; // process.nextTick error, or 'error' event on first tick
remote:         ^
remote: Error: Cannot find module 'socket.io-client'
remote:     at Function._resolveFilename (module.js:320:11)
remote:     at Function._load (module.js:266:25)
remote:     at require (module.js:348:19)
remote:     at Object.<anonymous> (/home/node/node-service/releases/20110702061403/node_modules/socket.io/lib/socket.io.js:12:14)
remote:     at Module._compile (module.js:404:26)
remote:     at Object..js (module.js:410:10)
remote:     at Module.load (module.js:336:31)
remote:     at Function._load (module.js:297:12)
remote:     at require (module.js:348:19)
remote:     at Object.<anonymous> (/home/node/node-service/releases/20110702061403/node_modules/socket.io/index.js:8:18)
remote: [ Jul  2 06:14:04 Stopping because all processes in service exited. ]
remote: [ Jul  2 06:14:04 Executing stop method (:kill). ]
remote: [ Jul  2 06:14:04 Executing start method ("env `cat /home/node/node-service/profile` /opt/nodejs/v0.4.7/bin/node /home/node/node-service/releases/20110702061403/server.js &"). ]
remote: [ Jul  2 06:14:04 Method "start" exited with status 0. ]
remote: 
remote: node.js:134
remote:         throw e; // process.nextTick error, or 'error' event on first tick
remote:         ^
remote: Error: Cannot find module 'socket.io-client'
remote:     at Function._resolveFilename (module.js:320:11)
remote:     at Function._load (module.js:266:25)
remote:     at require (module.js:348:19)
remote:     at Object.<anonymous> (/home/node/node-service/releases/20110702061403/node_modules/socket.io/lib/socket.io.js:12:14)
remote:     at Module._compile (module.js:404:26)
remote:     at Object..js (module.js:410:10)
remote:     at Module.load (module.js:336:31)
remote:     at Function._load (module.js:297:12)
remote:     at require (module.js:348:19)
remote:     at Object.<anonymous> (/home/node/node-service/releases/20110702061403/node_modules/socket.io/index.js:8:18)
remote: [ Jul  2 06:14:05 Stopping because all processes in service exited. ]
remote: [ Jul  2 06:14:05 Executing stop method (:kill). ]
remote: [ Jul  2 06:14:05 Restarting too quickly, changing state to maintenance. ]
remote: \* \* *
remote: 
remote: Rolling back to 20110702055505 ... (please wait)
remote: svccfg: Unable to stat file /home/node/node-service/releases/20110702055505.xml.  No such file or directory
remote: svcadm: Instance "svc:/site/node-service:default" is in maintenance state.
remote: Rollback failed (old server did not start properly).
remote: \* \* *
remote:     at Object.<anonymous> (/home/node/node-service/releases/20110702061403/node_modules/socket.io/index.js:8:18)
remote: [ Jul  2 06:14:05 Stopping because all processes in service exited. ]
remote: [ Jul  2 06:14:05 Executing stop method (:kill). ]
remote: [ Jul  2 06:14:05 Restarting too quickly, changing state to maintenance. ]
remote: [ Jul  2 06:14:05 Leaving maintenance because disable requested. ]
remote: [ Jul  2 06:14:05 Disabled. ]
remote: [ Jul  2 06:14:15 Enabled. ]
remote: [ Jul  2 06:14:15 Executing start method ("env `cat /home/node/node-service/profile` /opt/nodejs/v0.4.7/bin/node /home/node/node-service/releases/20110702061403/server.js &"). ]
remote: chdir: No such file or directory
remote: [ Jul  2 06:14:15 Method "start" exited with status 96. ]
remote: \* \* *
To node@livelog.no.de:repo
   db7a44d..e9c0488  master -> master

**Comment by SpingSproutAce** [comment]
http://livelog.no.de

**Comment by SpingSproutAce** [comment]
도메인이 바껴서 로그인이 안됨;

**Comment by keesun** [comment]
http://wiki.joyent.com/display/node/Installing+MongoDB+on+a+Node.js+SmartMachine

몽고DB 설치완료.

**Comment by keesun** [comment]
몽고DB 백업 완료. 그런데.. 그걸 까먹었다. live.log 페북 앱 계정이 내 계정이 아니었나보군. 페북앱이랑 트윗앱 도메인 좀 바꿔주라~

**Comment by isyoon** [comment]
springsprout 개정임.;; 일단 업데이트 갑니다;

**Comment by isyoon** [comment]
바꾸긴 했는데.. 2개를 만들어서 개발이랑... 운영이랑 다르게 가져가야 할듯..
일단.. livelog.no.de 이녀석으로 전격 교체!!
