### ISSUE TITLE
로그인 정책

### ISSUE THREAD

**Issue by keesun** [SpingSproutAce/rtfeedback#19]
1. 로그인 해야지만 보게하자.
2. 로그인 없이 목록과 댓글 보게하자. 글 쓸때만 로그인 시키자.

**Comment by outsideris** [comment]
난 2번쪽....
- 요즘 SNS쪽에 스팸도 많고 해서(페이스북이 특히...) 서비스의 특징을 잘 모르는 상태에서는 SNS로 로그인하기가 꺼려짐.
- 로그인이라는 액션을 끌어내기 위해서는 사용자가 어떤 서비스인지 파악할 수 있어야 함
- 일반적으로 로그인해서 적극적으로 사용하는 사용자보다 보는 사람들이 더 많음
- 보다가 말하고 싶어져서 글을 쓸수도 있음
- 뷰는 열어주는게 전파의 속도가 더 좋다고 생각함..

**Comment by keesun** [comment]
gg... 2번으로 합시다.ㅋㅋ

**Comment by outsideris** [comment]
그냥 내가 생각하는걸 설명한건데 ㅋㅋ

**Comment by SpingSproutAce** [comment]
ㅇㅇ저도 2번이 좋은것 같아요.
