### ISSUE TITLE
앱 이름 정하기

### ISSUE THREAD

**Issue by keesun** [SpingSproutAce/rtfeedback#2]
뭔가 의미 있는 이름이면서 간단하고 쉬운 이름으로!

**Comment by keesun** [comment]
부메랑 어때.. Boomerang.
부메랑을 던지고 받듯이 피드백을 주고 받으라는 뜻.

**Comment by isyoon** [comment]
console.log나 ㅋㅋ node.log;
어때요 ㅋㅋㅋㅋ
js.log ? 
먼가 우리도 .을 이용해서 하면 어떨까요 ? ㅋㅋ
boomerang.log 넘긴데..ㅋㅋ
난 subfix .log로 하고 싶고. 형이 prefix정해요 ㅋㅋ

**Comment by keesun** [comment]
live.log 어때

사업이랑도 어울려야 할텐데, live.conference.log는 이전에 말한 서비스고, live.issue.log도 이전에 말했지.

**Comment by isyoon** [comment]
live.log 합시다.ㅋㅋㅋ
