### ISSUE TITLE
글종류 아이콘과 사용자 아이콘...

### ISSUE THREAD

**Issue by outsideris** [SpingSproutAce/rtfeedback#20]
그동안 소스랑 히스토리를 몰라서 재이슈인지는 모르겠지만.. ㅎㅎ

현재 글의 좌측의 글의 종류아이콘이 나타나고 하단에 사용자 아이콘이 나오는데
일반적인 서비스들이 좌측에 사용자 아이콘이 나타나는 UI에 익숙해져서 그런지 모르겠는데
이번에 써보니 약간 헷갈리는 기분이 들었음...

같은 종류의 글을 쓴 사람인데 왠지 자꾸 같은 사람이 쓴것처럼 느껴지고(어느글이 누구의 글인지 확인하는 신경을 써야하는 느낌이 있었음...)
일반적으로 사람들이 서비스가 배정해준 카테고리를 잘 따라서 글을 쓰지 않는다는 점에서 글의 종류보다는 누가 썼는지가 좀더 중요하지 않은가 싶은데 어떻게들 생각하는지.. ㅎ

**Comment by keesun** [comment]
#10번에서 이야기하죠. 이건 종료시킬께요.
