### ISSUE TITLE
타임라인....

### ISSUE THREAD

**Issue by outsideris** [SpingSproutAce/rtfeedback#21]
이슈라고 하긴 그렇지만 딱히 커뮤니케이션 공간은 없어서 ㅎㅎㅎ

기선이한테 뒷풀이때 잠시 얘기했었는데
A List Apart에서 [대화는 새로운 형태의 관심입니다](http://tranbot.net/ALA/conversation-is-the-new-attention/)라는 글의 테스트로 [Donahue](http://go.donahueapp.com/presentations/view/tosstheprojector/points/1)라는 시스템을 만들었음. 하고 싶었던건 livelog랑 상당히 비슷한것 같고... 발표와 연계된 타임라인을 가지고 있다는게 흥미로움.

이 시스템도 node.js에 socket.io로 만들어진 것으로 알고 있음.

**Comment by outsideris** [comment]
이건 딴얘긴데... 이거 private 저장소인데 fork를 하면 어떻게 되는거지? 내계정에 private로 생기나?

**Comment by keesun** [comment]
글쎼요; 포크따면 어떻게 되요??

**Comment by keesun** [comment]
People need to _react_ to interesting things.

진짜 라이브.로그랑 비슷하군요...

**Comment by isyoon** [comment]
Agenda 레이블 만들었어요 ㅎㅎ
수다 꺼리는 Agenda를 이용하시면 될듯합니다!

그나저나 위에 서비스 첨보고 머하는거지 ;; 한참을 방황했다는..ㅋㅋ 디자인은 이뿌네요 ㅎㅎ

**Comment by outsideris** [comment]
어제 포크 테스트 해봤는데 내 계정하위에 private로 생김..

**Comment by isyoon** [comment]
글쿤요 ㅎㅎ 그럼 이제 각자.. 다 포크해서 작업할까요?ㅋㅋ
네트워크 이미지 이뿌게 나오게?;;

**Comment by keesun** [comment]
그.. 그럴까?? pull request는 그럼 누가 수락해? SpringSprutAce 계정으로 들어가서 수락해야 되나;?

**Comment by outsideris** [comment]
pull request에 pull request 버튼이 있는걸로 봐서는 각자의 계정으로 수락이 가능할것 같기도..
근데 자기계정으로 푸시하는데도 네트워크 이미지가 모두 SpringSproutAce로 나오네... 
원래 그런건가?

**Comment by isyoon** [comment]
원래 포크해서 온거는 따로 나와야 하는거 아닌가요 ? ;

**Comment by keesun** [comment]
기본 계정으로는 private repo를 못가지는데 fork를 딴거니깐.. SpringSproutAce의 private repo로 잡히는건 아닐까요?

**Comment by isyoon** [comment]
네트워크 그래프의 비밀... 
풀리퀘스트 받은 내역이 나오는 거였음.. ㅡ.ㅡ;

**Comment by outsideris** [comment]
어라 이제 이쁘게 나오네...
