### ISSUE TITLE
로그인 버튼 통일

### ISSUE THREAD

**Issue by keesun** [SpingSproutAce/rtfeedback#23]
페북은 log in
트위터는 sign in 
인것 같은데.. 이 거 통일하는게 좋을듯..

**Comment by isyoon** [comment]
그게 컨셉인데요?;; 페북은 로그인이라고 하구.. 트윗은 사인인 이라고 한단말이죠;;

**Comment by keesun** [comment]
그렇군. 그럼 내비두지뭐!
