### ISSUE TITLE
node_modules 제거하기

### ISSUE THREAD

**Issue by outsideris** [SpingSproutAce/rtfeedback#28]
모듈은 package.json에 표시하고 모듈들은 형상관리에서 제거하기

**Comment by outsideris** [comment]
모듈이 형상관리에 올라가 있는게 이상해서 삭제하고 package.json에 표시함
소스 업데이트 받으면 node_modules가 지워질 것이므로 npm install 로 재설치해야할것임
작업하고 보니 내 로컬환경이 제대로 구성되어 있지 않아서 테스트 부탁....
(connect-mongodb말고는 최신버전으로 설치되게 해서 혹 문제 발생하면 변경해야함)

**Comment by isyoon** [comment]
ImYoon@newYoonMac livelog $ npm update
node-uuid@1.2.0 ./node_modules/node-uuid 
oauth@0.9.2 ./node_modules/oauth 
jade@0.13.0 ./node_modules/jade 
express@2.4.2 ./node_modules/express 
├── mime@1.2.2
├── connect@1.6.0
└── qs@0.2.0
socket.io@0.7.7 ./node_modules/socket.io 
├── redis@0.6.0
├── policyfile@0.0.3
└── socket.io-client@0.7.4

connect-mongodb@0.4.0 ./node_modules/connect-mongodb 
├── connect@1.6.0 (mime@1.2.2 qs@0.2.0)
└── mongodb@0.9.6-7
mongoose@1.7.2 ./node_modules/mongoose 
├── hooks@0.1.9
└── mongodb@0.9.6-7

install 말고 npm update 로 했습니다!

일단 큰문제 없이 잘돌아가네요! 감사합니다 :-)

**Comment by isyoon** [comment]
이녀석 에디터가 @을 메일로 익식해서 ;; mailto 를 줘버리는 군요 ;;

**Comment by outsideris** [comment]
ㅋㅋㅋㅋㅋ 정규식 잘 만들었네..

**Comment by keesun** [comment]
저거 입력될 때 서버에서 입히는게 아니라 자바스크립트로 화면에서 하는거죠?

**Comment by outsideris** [comment]
소스보기해도 a태그 되어 있는거 보면 얘네는 서버에서 하는듯?
