### ISSUE TITLE
DDOS 공격은 어떻게 막지?

### ISSUE THREAD

**Issue by keesun** [SpingSproutAce/rtfeedback#4]
혹시라도 유료 서비스 중인데, 악의적인 사용자가 일부러 다운 시키려고 DDOS를 시도할 수도 있지 않을까?ㅋ

**Comment by outsideris** [comment]
DDOS는 어플리케이션단에서는 막을 수 없는거 아닌가? ㅎ
클라우드 벤더에서 막아줄듯.... ㅎㅎ

**Comment by keesun** [comment]
넹 호스팅 업체 생겼으니 이슈 종료.
